name: Publish Fork

on:
  push:
    branches: ['build/.*']
  pull_request:
    branches: ['build/.*']

jobs:
  cancel-previous:
    name: Cancel Stale In-progress Builds
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Cache Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Run Static Checks
        run: ./gradlew check --parallel

  deploy:
    name: Publish Fork
    runs-on: macos-latest
    if: github.event_name == 'push'
    needs: [ static_checks ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Configure JFrog credentials
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          mkdir -p ~/.gradle
          echo cruGlobalMavenRepositoryUsername=$JFROG_USERNAME >> $HOME/.gradle/gradle.properties
          echo cruGlobalMavenRepositoryPassword=$JFROG_PASSWORD >> $HOME/.gradle/gradle.properties
      - name: Publish library
        run: ./gradlew :antlr-kotlin-runtime:publish --parallel
