name: Publish Fork

on:
  push:
    branches: ['build/*']
  pull_request:
    branches: ['build/*']

jobs:
  cancel-previous:
    name: Cancel Stale In-progress Builds
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-
      - name: Run Static Checks
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --parallel

  deploy:
    name: Publish Fork
    runs-on: macos-latest
    if: github.event_name == 'push'
    needs: [ static_checks ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish library
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :antlr-kotlin-runtime:publish --parallel
        env:
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryUsername: ${{ secrets.JFROG_USERNAME }}
          ORG_GRADLE_PROJECT_cruGlobalMavenRepositoryPassword: ${{ secrets.JFROG_PASSWORD }}
